spring.application.name=epic3

spring.datasource.url=jdbc:postgresql://localhost:5432/reviews_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true